@startuml
left to right direction
skinparam packageStyle rectangle
actor Авторизованный_пользователь
actor Неавторизованный_пользователь
rectangle {

'Авторизованный пользователь

    Авторизованный_пользователь --> (Работа с папками)
    (Работа с папками) ..> (Создание) : <<include>>
    (Работа с папками) ..> (Удаление) : <<include>>

    Авторизованный_пользователь --> (Работа с файлами)
    (Работа с файлами) ..> (Копировать ссылку) : <<include>>
    (Работа с файлами) ..> (Переименовать) : <<include>>
    (Работа с файлами) ..> (Добавить в избранное) : <<include>>


'Неавторизованный пользователь

    Неавторизованный_пользователь --> (Авторизация)

    Неавторизованный_пользователь --> (Выбор тарифного плана)
    (Выбор тарифного плана) ..> (Плюс) : <<include>>
    (Выбор тарифного плана) ..> (Семейный) : <<include>>

    Неавторизованный_пользователь --> (Просмотр страниц с информацией)

    Неавторизованный_пользователь --> (Смена языка)

}
@enduml